name: Take Cover / Stand Up (Action)
tags: [combat, skirmish]
duration: Instant
cost: Minor Action
trigger: "When you drop Prone or rise from Prone status."
rules: |
  As a Minor Action, become [[condition-prone|Prone]] *or* recover from the Prone Condition.
