name: Jump (Action)
tags: [combat, movement, skirmish]
duration: Instant
cost: Minor Action
trigger: "When you attempt a jump."
save: null
rules: |
  Attempt a jump as per the rules for [[movement|jumping]].
