name: Faction Activity (Action)
tags: [factions, leadership]
duration: Variable
trigger: "When your Faction undertakes an unusual action that doesn't fit a predefined action."
rules: |
  Lots of weird Faction actions won't cleanly fall into any other niche. In these cases, a GM may determine a **Duration** based on the nature of the act & use the Success Save template table to determine the general outcome.

  When the Duration elapses, Save.

  | Result | Effect |
  | :----: | ------ |
  | Crit (≥12) | The action succeeds twice as well as anyone hoped for, or in an exceptional way. If the outcome *directly* benefited or aided other Factions, they grow Pleased. |
  | Pass (8–11) | The action succeeds exactly as intended. |
  | Seven (7) | The action succeeds half as well as intended. |
  | Failure (3–6) | A new, secondary problem has emerged that prevents the completion of the action until resolved. Pick a Faction (*preferably an Idle one that would be opposed to the action*) that's to blame for or related to the new problem. |
  | Fumble (≤2) | The action fails catastrophically. The worst possible thing that could happen (for you & the local environment) happens. |
