name: Create Subfaction (Action)
tags: [factions, administration, leadership]
duration: Variable
trigger: "When you promote a Retainer and gift them a Capital to form a new Subfaction."
rules: |
  To create a new Subfaction, you must:

  1. **Promote a Leader**: Promote one of your Retainers or someone else you know to the position of Leader.
  2. **Define its role**: Determine the nature of the Subfaction. This has a direct impact on its actual ability to serve you; you are shaping the structure of the institution, and that's limited by what your realm is actually capable of supporting.
  3. **Gift a Capital**: A physical Settlement or other Capital (such as a castle, or a building or district inside a larger Settlement) suited to its nature must be gifted to the Leader. The new Capital must:
     - Be *controlled* by you.
     - Possess Families at least equal to the minimum Families required to support a Subfaction of the Level you wish to create — you can't make a high-Level Faction without gifting them a *real* Capital.
     - Be *unclaimed* — not currently be the Capital of *any other* active Faction, excepting claimed subdivisions (i.e. buildings in a city, offices in a building).
     - Come with any *territory or land* that would *de jure* be part of its domain (you can't gift a castle without gifting the lands around it, after all).
  4. **Transfer assets**: You may need to transfer assets such as Settlements located within the territory granted to a Subfaction.

  The **Duration** for creating a new Subfaction is set based on the table below & the Followers in the new Capital.

  | Followers in Capital | Faction Level | Duration |
  | -------------------- | :-----------: | -------- |
  | 1+                   |      2        | 1 day    |
  | 3+                   |      3        | 1 day    |
  | 10+                  |      4        | 2 days   |
  | 30+                  |      5        | 2 days   |
  | 100+                 |      6        | 3 days   |
  | 300+                 |      7        | 4 days   |
  | 1,000+               |      8        | 5 days   |
  | 3,000+               |      9        | 10 days  |
  | 10k+                 |      10       | 20 days  |
  | 30k+                 |      11       | 30 days  |
  | 100k+                |      12       | 100 days |
  | 300k+                |      13       | 200 days |
  | 1,000k+              |      14       | 1 year   |

  When the Duration elapses, the Subfaction is automatically formed; no Save required.
