name: Jump (Action)
tags: [combat, movement, skirmish]
duration: Instant
cost: Minor Action
trigger: "When you attempt a jump."
save: null
rules: |
  As a Minor Action, attempt a jump. Horizontal jumps cover a number of feet equal to half your Run score on a running start, or one quarter standing still. Vertical jumps reach one quarter of those distances. Characters who are [[encumbered|encumbered]] halve their effective jumping distance.